"""changed scheduled_workout.status to enum and removed relethionship between exercises and workout_log_items

Revision ID: 1e45cb9d6801
Revises: c26e434c9489
Create Date: 2025-12-11 19:33:25.141759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e45cb9d6801'
down_revision: Union[str, Sequence[str], None] = 'c26e434c9489'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scheduled_workout', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('pending', 'stopped', 'done', 'missed', 'cancelled', name='workout_status_enum', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_constraint(op.f('workout_log_items_exercise_id_fkey'), 'workout_log_items', type_='foreignkey')
    op.drop_column('workout_log_items', 'exercise_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_log_items', sa.Column('exercise_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('workout_log_items_exercise_id_fkey'), 'workout_log_items', 'exercise', ['exercise_id'], ['id'])
    op.alter_column('scheduled_workout', 'status',
               existing_type=sa.Enum('pending', 'stopped', 'done', 'missed', 'cancelled', name='workout_status_enum', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    # ### end Alembic commands ###
