"""renewed relationship workout_log_items and exercise

Revision ID: 26c51db1faa6
Revises: 1e45cb9d6801
Create Date: 2025-12-13 00:46:44.819916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26c51db1faa6'
down_revision: Union[str, Sequence[str], None] = '1e45cb9d6801'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
