"""Adjusted tables WorkoutLogItems and WorkoutItems

Revision ID: 637c65a838d8
Revises: 545dd28a5224
Create Date: 2025-12-05 16:37:10.104579

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "637c65a838d8"
down_revision: Union[str, Sequence[str], None] = "545dd28a5224"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workout_log_items",
        sa.Column("workout_item_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        None,
        "workout_log_items",
        "workout_items",
        ["workout_item_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "workout_log_items", type_="foreignkey")
    op.drop_column("workout_log_items", "workout_item_id")
    # ### end Alembic commands ###
