"""Added relathionship between Exercises and Users

Revision ID: c26e434c9489
Revises: 7277e45d1b08
Create Date: 2025-12-06 18:41:49.328798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c26e434c9489'
down_revision: Union[str, Sequence[str], None] = '7277e45d1b08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('owner_id', sa.Integer(), server_default=sa.text('null'), nullable=True))
    op.add_column('exercise', sa.Column('is_global', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_foreign_key(None, 'exercise', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exercise', type_='foreignkey')
    op.drop_column('exercise', 'is_global')
    op.drop_column('exercise', 'owner_id')
    # ### end Alembic commands ###
