"""renewed relationship workout_log_items and exercise1

Revision ID: fd219c5a0c77
Revises: 26c51db1faa6
Create Date: 2025-12-13 00:49:34.813192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd219c5a0c77'
down_revision: Union[str, Sequence[str], None] = '26c51db1faa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_log_items', sa.Column('exercise_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'workout_log_items', 'exercise', ['exercise_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workout_log_items', type_='foreignkey')
    op.drop_column('workout_log_items', 'exercise_id')
    # ### end Alembic commands ###
